version: '1.0'
name: pipeline-20220408
displayName: pipeline-20220408
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - ''
stages:
  - name: stage-b8f65957
    displayName: docker-build
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@docker
        name: build_docker
        displayName: 镜像构建
        type: account
        repository: https://gitee.com/meadhu/tornadoadmin.git
        username: meadhu
        password: abcd1234
        tag: latest
        dockerfile: ./Dockerfile
        isCache: true
  - name: stage-031db9d4
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: publish@general_artifacts
        name: publish_general_artifacts
        displayName: 上传制品
        dependArtifact: BUILD_ARTIFACT
        artifactName: output
  - name: stage-bf361790
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: shell@agent
        name: execute_shell
        displayName: Shell 脚本执行
        hostGroupID: gitee-go
        script: |-
          # 请在此输入您想执行的脚本
          echo 'Hello Gitee!'
          sh start.sh
permissions:
  - role: admin
    members: []
